[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/agentsocietyenv"]

[tool.uv.sources]
agentsociety = { workspace = true }
agentsociety-community = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.13",
    "sphinx>=8.2.3",
]
